{{- if .Values.pod.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.pod.name }}
spec:
  containers:
    - name: {{ .Values.pod.containerName }}
      image: {{ .Values.pod.imageName }}
{{- end }}
